### ISSUE TITLE
ProcessData

### ISSUE THREAD

**Issue by SammyDerksen** [Software-Engineering-DHBW/-L-earn#18]
data
bannedProcesses

- updateData()
- checkProcesses()

Welche Prozesse sind wichtig?
Welche sind Hintergrundprozesse?
Prozesse von gleichem Programm erkennen
-> irrelevante Prozesse aussortieren

**Comment by reusdomi** [comment]
Um killProcess()-Funktion erweitern

**Comment by reusdomi** [comment]
date als Atribut einfügen und runtime bei Tageswechsel überprüfen und aktualisieren
